// AUTO-GENERATED by MSBuild target when $(ShaPrintPsk) is set.
// DO NOT edit manually — changes will be overwritten.
// When $(ShaPrintPsk) is NOT set, Psk is empty and fallback chain applies.

namespace ShaPrint.Core
{
    internal static class BuildTimeSecrets
    {
        /// <summary>
        /// Embedded at compile time from GitHub Actions secret via MSBuild.
        /// Empty string = not set (fall through to env var / file / auto-gen).
        /// </summary>
        internal const string Psk = "";
    }
}
